import './js/darkTheme';
import './js/refs';
import './js/render-main-gallery';
import './js/modal-window';
import './js/all-requests';
import './js/autorization-modal';
import './js/categories-list-markup';
import './js/header';
import './js/support-new';
